### ISSUE TITLE
Extend + add list methods (ShiftN, PopN, Concat, Repeat, Splice, Slice, FlattenN)

### ISSUE THREAD

**Issue by MajorLift** [poteat/hkt-toolbelt#16]
Edit: Implemented in #17.

---

I'd love to adapt and add the following as list methods. Let me know if it aligns with your plans + any feedback. 

- Shift: can optionally dequeue multiple items from head of list.
- Pop: can optionally pop multiple items from tail of list.
- Concat: concatenates two lists.
- Splice: same behavior as `Array.prototype.splice()`, but with `START` and `DEL_COUNT` constrained as `NaturalNumber`.
- Repeat: similar to `List._$times` method, but fills list with one item. 
- ~~ToString: same behavior as `Array.prototype.join()`.~~
  - Looks like this could be handled with `String.fromList` and `String.join`. Would a wrapper method `List.Join` that uses those two under the hood make sense?

P.S. Is there a safe way to use List methods on DigitList types?

```ts
type Shift<T extends unknown[], N extends number = 1> = 
  N extends 0 
    ? T 
    : T extends [infer _, ...infer Rest]
      ? Shift<Rest, Subtract<N, 1>>
      : [];

type Pop<T extends unknown[], N extends number = 1> = 
  N extends 0 
    ? T
    : T extends [...infer Rest, infer _]
      ? Pop<Rest, Subtract<N, 1>> 
      : [];

type Concat<T extends unknown[], U extends unknown[]> = 
  [...T, ...U];

type Splice<
  T extends unknown[], 
  START extends number = 0, 
  DEL_COUNT extends number = 0, 
  INSERTS extends unknown[] = [],
  PRE extends unknown[] = [],
  POST extends unknown[] = T,
  RESULT extends unknown[] = 
    Comparator<START, T["length"]> extends 0 | 1
      ? [...T, ...INSERTS]
      :  DEL_COUNT extends 0
        ? START extends 0
          ? [...PRE, ...INSERTS, ...POST]
          : Splice<T, Subtract<START, 1>, 0, INSERTS, [...PRE, POST[0]], Shift<POST>>
        : START extends 0
          ? [...PRE, ...INSERTS, ...Shift<POST, DEL_COUNT>]
          : Splice<T, Subtract<START, 1>, DEL_COUNT, INSERTS, [...PRE, POST[0]], Shift<POST>>
> = RESULT;

type Repeat<N extends number, T extends unknown = null, M extends T[] = []> = 
  M["length"] extends N ? M : Repeat<N, T, Push<M, T>>;

type ToString<T extends any[], DELIM extends string = ''> = 
  T extends [T[0], ...infer Rest extends unknown[]]
    ? `${T[0]}${Rest extends [] ? '' : `${DELIM}${ToString<Rest, DELIM>}`}`
    : '';
```
---
Edit:
- Slice: Extend current implementation to support all features of `Array.prototype.slice()` including negative indices.
- Flatten: `Array.prototype.flat()`. Might be useful to have `Flatten` (flatten single depth level) and `FlattenN`.

```ts
type Slice<
  T extends unknown[], 
  START extends number = 0, 
  END extends number = T["length"],
  START_POS extends number = IsNonNegative<START> extends true 
    ? START
    : Subtract<T["length"], Absolute<START>>,
  END_POS extends number = IsNonNegative<END> extends true 
    ? Subtract<T["length"], END>
    : Absolute<END>,
  RESULT = OutOfBounds<START_POS, END_POS, [0, T["length"]]> extends true 
    ? [] 
    : Shift<Pop<T, END_POS>, START_POS>,
  > = RESULT;

type OutOfBounds<LO extends number | never, HI extends number | never, RANGE extends number[]> = 
  LO extends never ? true : HI extends never ? true
    : LessThan<LO, RANGE[0]> extends true ? true 
    : LessThan<RANGE[1], HI> extends true ? true
      : false;

type Flatten<T extends unknown[]> = 
  T extends [] ? []
  : T extends [infer H, ...infer R]
    ? H extends unknown[]
      ? [...Flatten<H>, ...Flatten<R>]
      : [H, ...Flatten<R>]
    : []
```

**Comment by poteat** [comment]
I would be very excited to get these in!

One note: re the recent advancements of partial application, "optional" parameters are not longer really possible. So I would be in favor of `Shift`, and perhaps separately `ShiftN` or `ShiftN`, where the first parameter is the N value:

```
type Shift2 = $<List.ShiftN, 2>

type Result = $<Shift2, ["x", "y", "z"]> // "z"
```

As well, for unused inferred variables (such as `infer _`), my understanding is that such inference placeholders may be replaced with `unknown` for a semantically equivalent representation.

Re `DigitList`, there is some 'duplication' between modules because there are certain assumptions that can be made within `DigitList` for more performant types (which are of course very much needed for performant arithmetic).

Finally, re `List.ToString`, I think a wrapper approach is fine. I think aliases are better if folks find it intuitive. On the other hand, having 'one way to do something' is valuable. I'm not sure whether `List.ToString` or `List.Join` would be better in terms of semantics.

The difference between `String.FromList` and `String.Join` is that the latter has special logic to handle and generate template strings, i.e. `$<$<String.Join, " ">, ["hello", string, "world"]>` results in the literal string template `"hello ${string} world"`. The former is only used internally in cases where we don't support template strings (e.g. arithmetic), for performance optimization.

**Comment by MajorLift** [comment]
I like the idea of implementing ShiftN with currying. `unknown` for `infer _` is also good to know and I'll keep it in mind. 
 
I agree with the value of having one way of doing things. Maybe providing `List.ToString` as a simple alias for `String.FromList`, and maintaining `String.Join` as the only way to do joins might be an approach.

**Comment by MajorLift** [comment]
It appears that `List.Slice` implements the exact functionality for `ShiftN` already. Would you be on board with adapting that to `List.ShiftN`, `List.PopN`, and implementing a new `List.Slice` that does `Array.prototype.slice()`?
